clear all
dx=0.001;
dataX=0:dx:1;
snr=20;
qcCoefs=[4,5,0.3,3,0.6];
subplot(10,1,1)%输出分块
A=crcbgenqcsig(dataX,snr,qcCoefs);
plot(dataX,A)
subplot(10,1,2)%输出分块
A=Sinusoidal(dataX,snr,qcCoefs);
plot(dataX,A)
subplot(10,1,3)%输出分块
A=Linearchirp(dataX,snr,qcCoefs);
plot(dataX,A)
subplot(10,1,4)%输出分块
A=SineGaussian(dataX,snr,qcCoefs);
plot(dataX,A)
subplot(10,1,5)%输出分块
A=Frequencymodulated(dataX,snr,qcCoefs);
plot(dataX,A)
subplot(10,1,6)%输出分块
A=Amplitudemodulated(dataX,snr,qcCoefs);
plot(dataX,A)
subplot(10,1,7)%输出分块
A=AMFMsinusoid(dataX,snr,qcCoefs);
plot(dataX,A)
subplot(10,1,8)%输出分块
A=Lineartransient(dataX,snr,qcCoefs);
plot(dataX,A)
subplot(10,1,9)%输出分块
A=Exponentiallydamped(dataX,snr,qcCoefs);
plot(dataX,A)
subplot(10,1,10)%输出分块
A=FM(dataX,snr,qcCoefs);
plot(dataX,A)

